### ISSUE TITLE
As a shop owner, im getting an error when checking the accepted terms and conditions

### ISSUE THREAD

**Issue by joeltejeda** [Subscribie/subscribie#1122]
**Is your feature request related to a problem? Please describe.**
As a Shop Owner, Im able to attach a agreedable terms and service document into a plan, but when the plan is edited the subscription of the plan is no longer attached to the document. 
The error:
```
 jinja2.exceptions.UndefinedError: sqlalchemy.orm.collections.InstrumentedList object has no element 0
```

Steps to reproduce: 

1. Attach a document into a plan
2. checkout to the plan 
3. edit the plan 
4. go to http://<your-shop>/admin/list-documents?filter=terms-and-conditions-agreed

**Describe the solution you'd like**
Been able to keep the document attached to the plan even if the shop owner edits the plan. 

**Additional context**
The code having the problem: 
https://github.com/Subscribie/subscribie/blob/master/subscribie/blueprints/admin/templates/admin/documents/list_documents.html#:~:text=document.subscriptions%5B0%5D.person.id

What values are inside the ```document``` variable: 
https://github.com/Subscribie/subscribie/blob/8fb1d5663f8703441b44114f9b1dead1af92bce7/subscribie/blueprints/admin/__init__.py#L770

Where do we have a similar code? Showing subscribers, but the main difference is that the subscription is attached to the subscribers and  cannot be changed. 

python:
https://github.com/Subscribie/subscribie/blob/8fb1d5663f8703441b44114f9b1dead1af92bce7/subscribie/blueprints/admin/__init__.py#L1246

Jinja
https://github.com/Subscribie/subscribie/blob/8fb1d5663f8703441b44114f9b1dead1af92bce7/subscribie/blueprints/admin/templates/admin/subscribers.html#L198

**Comment by chrisjsimpson** [comment]
>  im getting an error

Please state what the error is that will be helpful to re-produce.



Note:
On reflection I think a root cause here may be the fact we don't archive documents when a plan is archived, in the same way we archived plans.

For plans, when they are edited, [we mark the plan as archived](https://github.com/Subscribie/subscribie/blob/master/subscribie/blueprints/admin/__init__.py#L509) which preserves properties **_directly_** on [the plan model](https://github.com/Subscribie/subscribie/blob/master/subscribie/models.py#L566-L602).

What do we archive plans when they are edited? Answer: We must preserve plan information which may have subscribers, it is a violation to allow a shop owner to arbitrarily change the details of a subscribed plan (silly example: Customer signs up with a plan description of '100MB broadband', sign ups happen, but then the shop owner changes the description to  '10MB broardband'). By archiving plans, we preserve the statement of record.

The devil is in the details. Unless I'm mistaken, we currently do *not* preserve associated document information in the same way as we do for plan details on the plan model (e.g. plan title and plan description are preserved, [because they're directly on the `Plan` model](https://github.com/Subscribie/subscribie/blob/master/subscribie/models.py#L571-L572)- but that's not the case for relations such as documents)- and this is perhaps the core of the issue. 

Presently, as a customer when I sign up to a plan with documents attached, those documents could be changed (edited) after signing up- that must not be possible.

Therefore we probably must preserve - set  in stone- documents after signup, and also factor in the same process when a plan is archived (because when a plan is archived- you want to know *exactly* what documents said at the time of the archival, they mustn't change.
